services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
