name: Deploy to Cloudflare Pages
on:
  push:
    branches: [main]

permissions:
  contents: read
  deployments: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy to Cloudflare Pages

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build
            
            - name: Deploy to Cloudflare Pages
              uses: cloudflare/pages-action@v1
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                projectName: 'portfolio'
                directory: 'out'
                gitHubToken: ${{ secrets.GITHUB_TOKEN }}